### ISSUE TITLE
Support for SvelteKit, better abstractions for Sapper

### ISSUE THREAD

**Issue by tonyketcham** [tonyketcham/p5-svelte#34]
## The Problem
Using this component in SvelteKit & Sapper is incredibly verbose and negates the core point of this component - to abstract away the complexity of mounting p5 to a Svelte project. This component should be functionally hot-swappable between SvelteKit, Sapper, etc. with no special user config required.

## The Fix
The user should have an elegantly simple way to drop `p5-svelte` into any Svelte project. The API needs to be consistent as well as expanded to optionally allow direct access to the p5 instance running under the hood. The installation method needs to be redone to be universally adaptable while increasing both functionality and simplicity without introducing breaking changes.

**Comment by Lakedaemon** [comment]
Did you manage to make it work for sveltekit ? 
I would really like to use p5 in my sveltekit spas

**Comment by tonyketcham** [comment]
@Lakedaemon it took me a while to get around to it but yes!

Resolved in [`v3.0`](https://github.com/tonyketcham/p5-svelte/releases/tag/v3.0.0) 🎉
