### ISSUE TITLE
Typescript: Uncaught ReferenceError: p5 is not defined

### ISSUE THREAD

**Issue by lockykeaney** [tonyketcham/p5-svelte#64]
**Describe the bug**
Typescript project fails to load p5 on component mount saying the p5 variable, which must be the one passed from the component to the sketch function is undefined. Used the commands `yarn add p5-svelte` and `yarn add p5 -D`

**To Reproduce**
Create a new Typescript project and copy the example into App component

**Expected behavior**
p5.js to load.

**Screenshots**
![Screenshot 2021-07-19 170223](https://user-images.githubusercontent.com/12781843/126117020-a81d1818-9a97-41da-bb1c-7f1704292750.png)
![Screenshot 2021-07-19 170242](https://user-images.githubusercontent.com/12781843/126117023-ca75e5e6-ed91-4b85-abf1-b04c3063aba9.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome, Firefox

**Comment by tonyketcham** [comment]
Thanks for submitting. I'll take a look into this and I think it should be resolved in the next release

**Comment by tonyketcham** [comment]
Resolved in [`v3.0`](https://github.com/tonyketcham/p5-svelte/releases/tag/v3.0.0) 🎉
