### ISSUE TITLE
p5.loadSound is not defined.

### ISSUE THREAD

**Issue by hanbao-dev** [tonyketcham/p5-svelte#92]
**Describe the bug**
I'm unable to use the p5 sound library.

**To Reproduce**
Setup everything as the repository says. I'm not having any issues with the p5 default library, only with p5.sound.

**Errors**
`There's an error as "loadSound" could not be called as a function `
`p5.loadSound is not a function`

**Version**
`"p5": "^1.4.0",
"p5-svelte": "^2.2.2"`

**Comment by hanbao-dev** [comment]
Solution.

Import p5.Sound using the script tags in app.html.

Use any global variables in onMount(){}

**Comment by tonyketcham** [comment]
Connected to #24

**Comment by tonyketcham** [comment]
I know I haven't given this library the TLC it deserves over the past year - very sorry about that. I'll try to get v3.0 polished up and released over the next couple days which should handle this without any workarounds needed.

**Comment by 0p3r4t0r** [comment]
@danielstevenberger 
Would you mind sharing a little more detail on how you imported the script tag in app.html. I am placing the file in statis and then using `<script src="%sveltekit.assets%/p5.sound.js" />`. However this gives me an error `p5 is not defined`

**Comment by xpluscal** [comment]
@tonyketcham @danielstevenberger @0p3r4t0r any updages on this?
As mentioned, adding the p5 sound via app.html produces errors due to missing global p5
